"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

const API = process.env.NEXT_PUBLIC_AUDIOCHOICE_API_URL || "https://audiochoice-stg-api.grayocean-b35d4bf9.eastus.azurecontainerapps.io";
const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "105248861745-34kh2v9g9825kb1drs3jrgmijjum2p3o.apps.googleusercontent.com";
type Access = { userID: string; email: string; displayName: string; role: string; active: boolean };
type CatalogBook = { editionID: string; scanResultID: string; fingerprint: { title: string; author?: string; edition?: string; fileHash?: string }; scanDate: string; scannerVersion: string; eventCount: number; explorePublished: boolean; hasCoverArt: boolean; hasTranscript: boolean };
type Audit = { id: string; title: string; author?: string; edition?: string; candidateCount: number; reviewedCount: number; status: string; completedAt?: string; compensationAmount?: number; paymentStatus: string; reviewFocus?: string; reviewMediaStatus?: string };
type Payment = { assignmentID: string; auditorID?: string; auditorName?: string; auditorEmail?: string; title: string; edition?: string; status: string; completedAt?: string; amount?: number; paymentStatus: string; paymentDate?: string; paymentNote?: string };
type Dashboard = { scannedEditionCount: number; awaitingApprovalCount: number; readyToPayCount: number; readyToPayAmount: number; activeAuditorCount: number };

function formatMoney(value?: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value || 0); }
function formatDate(value?: string) { return value ? new Date(value).toLocaleDateString() : "—"; }
function download(name: string, value: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
declare global { interface Window { google?: any } }

export default function Home() {
  const [token, setToken] = useState(""); const [user, setUser] = useState<Access | null>(null); const [error, setError] = useState("");
  const [section, setSection] = useState("overview"); const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [catalog, setCatalog] = useState<CatalogBook[]>([]); const [audits, setAudits] = useState<Audit[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [selected, setSelected] = useState<CatalogBook | null>(null); const [detail, setDetail] = useState<any>(null); const [search, setSearch] = useState(""); const [users, setUsers] = useState<Access[]>([]); const [busy, setBusy] = useState(false); const [setup, setSetup] = useState(false);
  const call = async (path: string, init: RequestInit = {}, supplied = token) => { const r = await fetch(API + path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${supplied}`, ...init.headers } }); if (!r.ok) throw new Error(r.status === 401 ? "Your session expired. Please sign in again." : r.status === 403 ? "This account is not approved as an AudioChoice administrator." : "AudioChoice could not complete that request."); return r.status === 204 ? null : r.json(); };
  const load = async (supplied = token) => { const me = await call("/v1/internal/me", {}, supplied) as Access; if (me.role !== "admin") throw new Error("This account is not approved as an AudioChoice administrator."); setUser(me); const [summary, books, taskList, paymentList, people] = await Promise.all([call("/v1/internal/admin/dashboard", {}, supplied), call("/v1/internal/admin/catalog", {}, supplied), call("/v1/internal/audits", {}, supplied), call("/v1/internal/admin/payments", {}, supplied), call("/v1/internal/admin/users", {}, supplied)]); setDashboard(summary); setCatalog(books); setAudits(taskList); setPayments(paymentList); setUsers(people); };
  useEffect(() => { const saved = sessionStorage.getItem("audiochoice-admin-token"); if (saved) { setToken(saved); load(saved).catch(e => { sessionStorage.removeItem("audiochoice-admin-token"); setError(e.message); }); } }, []);
  const acceptToken = async (accessToken: string) => { sessionStorage.setItem("audiochoice-admin-token", accessToken); setToken(accessToken); try { await load(accessToken); } catch (e) { setSetup(true); throw e; } };
  const claimInitialAdmin = async () => { setBusy(true); try { const r = await fetch(API + "/v1/internal/bootstrap-admin", { method: "POST", headers: { Authorization: `Bearer ${token}` } }); if (!r.ok) throw new Error("An administrator is already configured. Ask an existing administrator to grant this account access."); setSetup(false); await load(token); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const login = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setError(""); try { const r = await fetch(API + "/v1/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); if (!r.ok) throw new Error("Email or password is incorrect."); await acceptToken((await r.json()).accessToken); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const googleLogin = async (credential: string) => { setBusy(true); setError(""); try { const r = await fetch(API + "/v1/auth/external", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: "google", authorizationCode: "", identityToken: credential, displayName: null }) }); if (!r.ok) throw new Error("Google sign-in could not be completed. Please try again."); await acceptToken((await r.json()).accessToken); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const refreshCatalog = async () => { try { setCatalog(await call(`/v1/internal/admin/catalog?search=${encodeURIComponent(search)}`)); } catch (e) { setError((e as Error).message); } };
  const openBook = async (book: CatalogBook) => { setSelected(book); setDetail(null); try { const [edition, filters] = await Promise.all([call(`/v1/internal/admin/catalog/${book.editionID}`), call(`/v1/internal/admin/catalog/${book.editionID}/filters`)]); setDetail({ edition, filters }); } catch (e) { setError((e as Error).message); } };
  const doTask = async (id: string, action: "approve" | "reject") => { try { await call(`/v1/internal/admin/audits/${id}/${action}`, { method: "POST" }); await load(); } catch (e) { setError((e as Error).message); } };
  const approveWithValue = async (audit: Audit) => { const proposed = window.prompt("Task value in USD. This becomes the auditor's pending payout once you approve it.", String(audit.compensationAmount ?? "")); if (proposed === null) return; const amount = Number(proposed); if (!Number.isFinite(amount) || amount < 0) { setError("Enter a valid task value of zero or more."); return; } try { await call(`/v1/internal/admin/audits/${audit.id}/compensation`, { method: "POST", body: JSON.stringify({ amount }) }); await call(`/v1/internal/admin/audits/${audit.id}/approve`, { method: "POST" }); await load(); } catch (e) { setError((e as Error).message); } };
  const markPaid = async (id: string) => { const note = window.prompt("Optional payment reference or note:", ""); if (note === null) return; try { await call(`/v1/internal/admin/audits/${id}/mark-paid`, { method: "POST", body: JSON.stringify({ note }) }); await load(); } catch (e) { setError((e as Error).message); } };
  const attachReviewAudio = async (id: string, file: File) => { setBusy(true); setError(""); try { const request = { fileName: file.name, contentType: file.type || "audio/mp4", fileSize: file.size }; const prepare = await call(`/v1/internal/admin/audits/${id}/review-source/authorization`, { method: "POST", body: JSON.stringify(request) }); const uploaded = await fetch(prepare.uploadURL, { method: prepare.method, headers: prepare.headers, body: file }); if (!uploaded.ok) throw new Error("The private M4B upload could not be completed. Please check your connection and try again."); await call(`/v1/internal/admin/audits/${id}/review-source/complete`, { method: "POST", body: JSON.stringify(request) }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  if (!user) return <main className="login"><section><div className="brand">Audio<span>Choice</span></div><p className="eyebrow">INTERNAL ADMIN PORTAL</p><h1>Run the operation in one place.</h1><p>Secure access for AudioChoice administrators only.</p>{setup ? <div className="setup"><h2>Set up the first administrator</h2><p>This only works once, while no AudioChoice admin account exists. It will grant admin access to the account you just signed in with.</p><button disabled={busy} onClick={claimInitialAdmin}>{busy ? "Setting up…" : "Make this my admin account"}</button></div> : <><GoogleLogin disabled={busy} onCredential={googleLogin}/><div className="or"><span>or use an internal password</span></div><form onSubmit={login}><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required/></label>{error && <p className="error">{error}</p>}<button disabled={busy}>{busy ? "Signing in…" : "Sign in securely"}</button></form></>}{error && setup && <p className="error">{error}</p>}</section></main>;
  const nav = [["overview", "Overview"], ["library", "Scan library"], ["audits", "Audit tasks"], ["payouts", "Payouts"], ["affiliates", "Affiliates"]];
  return <main className="app"><aside><div className="brand">Audio<span>Choice</span><small>ADMIN</small></div><nav>{nav.map(([key, label]) => <button key={key} className={section === key ? "active" : ""} onClick={() => setSection(key)}>{label}</button>)}</nav><div className="account"><strong>{user.displayName}</strong><span>{user.email}</span><button onClick={() => { sessionStorage.removeItem("audiochoice-admin-token"); location.reload(); }}>Sign out</button></div></aside><section className="content"><header><div><p className="eyebrow">INTERNAL OPERATIONS</p><h1>{nav.find(x => x[0] === section)?.[1]}</h1></div><span className="secure">● Private workspace</span></header>{error && <div className="error banner">{error}<button onClick={() => setError("")}>×</button></div>}{section === "overview" && <Overview dashboard={dashboard} catalog={catalog} openBook={openBook} setSection={setSection} />}{section === "library" && <Library catalog={catalog} search={search} setSearch={setSearch} refresh={refreshCatalog} openBook={openBook} />}{section === "audits" && <Audits items={audits} catalog={catalog} users={users} busy={busy} attach={attachReviewAudio} create={async (data) => { try { await call("/v1/internal/admin/audits", { method: "POST", body: JSON.stringify(data) }); await load(); } catch (e) { setError((e as Error).message); } }} action={doTask} approve={approveWithValue} />}{section === "payouts" && <Payouts items={payments} markPaid={markPaid} />}{section === "affiliates" && <Affiliates />}</section>{selected && <BookDrawer book={selected} detail={detail} close={() => setSelected(null)} call={call} />}</main>;
}
function GoogleLogin({ onCredential, disabled }: { onCredential: (credential: string) => void; disabled: boolean }) { const host = useRef<HTMLDivElement>(null); const [unavailable, setUnavailable] = useState(false); useEffect(() => { let active = true; const draw = () => { if (!active || !window.google || !host.current) return; window.google.accounts.id.initialize({ client_id: GOOGLE_CLIENT_ID, callback: (response: { credential?: string }) => response.credential && onCredential(response.credential) }); host.current.innerHTML = ""; window.google.accounts.id.renderButton(host.current, { type: "standard", theme: "outline", size: "large", text: "continue_with", shape: "rectangular", width: 360 }); }; if (window.google) { draw(); return () => { active = false; }; } const script = document.createElement("script"); script.src = "https://accounts.google.com/gsi/client"; script.async = true; script.onload = draw; script.onerror = () => setUnavailable(true); document.head.appendChild(script); return () => { active = false; }; }, [onCredential]); return <div className="google"><div ref={host} className={disabled ? "disabled" : ""}/>{unavailable && <button type="button" className="ghost" onClick={() => window.location.reload()}>Reload Google sign-in</button>}</div> }
function Overview({ dashboard, catalog, openBook, setSection }: any) { const cards = [[dashboard?.scannedEditionCount, "Scanned editions"], [dashboard?.awaitingApprovalCount, "Ready for review"], [dashboard?.readyToPayCount, "Approved, unpaid"], [formatMoney(dashboard?.readyToPayAmount), "Payouts due"]]; return <><div className="stats">{cards.map(([value, label]) => <article key={label}><strong>{value ?? "—"}</strong><span>{label}</span></article>)}</div><section className="panel"><div className="panelhead"><div><p className="eyebrow">SCAN LIBRARY</p><h2>Recently scanned editions</h2></div><button className="ghost" onClick={() => setSection("library")}>View library →</button></div><div className="bookgrid">{catalog.slice(0, 6).map((b: CatalogBook) => <button className="book" onClick={() => openBook(b)} key={b.editionID}><span className="cover">{b.hasCoverArt ? "ART" : "SCAN"}</span><strong>{b.fingerprint.title}</strong><small>{b.fingerprint.author || "Unknown author"}</small><em>{b.eventCount} filter events</em></button>)}</div></section><section className="notice"><strong>Admin control center</strong><p>Create quality-audit work, review completed audits, record payouts, and access generated scan materials. Original customer audiobook files are never exposed here.</p></section></> }
function Library({ catalog, search, setSearch, refresh, openBook }: any) { return <section className="panel"><div className="toolbar"><input value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === "Enter" && refresh()} placeholder="Search title, author, edition, or fingerprint" /><button onClick={refresh}>Search</button></div><div className="table">{catalog.map((b: CatalogBook) => <button key={b.editionID} className="row" onClick={() => openBook(b)}><span className="cover mini">{b.hasCoverArt ? "ART" : "SCAN"}</span><span><strong>{b.fingerprint.title}</strong><small>{b.fingerprint.author || "Unknown author"} · {b.fingerprint.edition || "Edition not specified"}</small></span><span>{b.eventCount} events<small>Scan {b.scannerVersion}</small></span><span>{formatDate(b.scanDate)}<small>{b.explorePublished ? "Explore published" : "Internal only"}</small></span><b>Open →</b></button>)}{!catalog.length && <p className="empty">No scan editions match that search.</p>}</div></section> }
function Audits({ items, catalog, users, create, action, approve, attach, busy }: any) { const [adding, setAdding] = useState(false); const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); create({ scanResultID: f.get("scanResultID"), auditorID: f.get("auditorID") || null, blindQC: f.get("blindQC") === "on", compensationAmount: Number(f.get("compensationAmount")) || null }); setAdding(false); }; return <><div className="panelhead"><div><p className="eyebrow">QUALITY CONTROL</p><h2>Audit assignments</h2><p className="muted">A completed scan creates a job here first. Attach its matching M4B to make the job available to auditors with event-only audio clips.</p></div><button onClick={() => setAdding(!adding)}>{adding ? "Cancel" : "Create audit task"}</button></div>{adding && <form className="create" onSubmit={submit}><label>Scanned edition<select name="scanResultID" required>{catalog.map((b: CatalogBook) => <option key={b.scanResultID} value={b.scanResultID}>{b.fingerprint.title} — {b.fingerprint.edition || "Unspecified edition"}</option>)}</select></label><label>Assign to auditor (optional)<select name="auditorID"><option value="">Leave available to claim</option>{users.filter((u: Access) => u.role === "auditor" && u.active).map((u: Access) => <option value={u.userID} key={u.userID}>{u.displayName}</option>)}</select></label><label>Flat compensation (USD)<input name="compensationAmount" type="number" min="0" step="0.01" placeholder="e.g. 12.00" /></label><label className="check"><input type="checkbox" name="blindQC" /> Blind quality-control task</label><button>Create task</button></form>}<section className="panel"><div className="table">{items.map((a: Audit) => <div className="row task" key={a.id}><span><strong>{a.title}</strong><small>{a.author || "Unknown author"} · {a.edition || "Edition not specified"}</small><small>{a.reviewFocus || "All detected events"}</small></span><span><b className="pill">{a.reviewMediaStatus === "waiting_for_source" ? "waiting for M4B" : a.status.replaceAll("_", " ")}</b><small>{a.reviewedCount}/{a.candidateCount} reviewed</small></span><span>{a.compensationAmount === undefined ? "Set after review" : formatMoney(a.compensationAmount)}<small>{a.paymentStatus}</small></span><span className="actions">{a.reviewMediaStatus === "waiting_for_source" && <label className="ghost">{busy ? "Attaching…" : "Attach matching M4B"}<input hidden type="file" accept=".m4b,audio/mp4" disabled={busy} onChange={e => { const file = e.currentTarget.files?.[0]; if (file) attach(a.id, file); e.currentTarget.value = ""; }} /></label>}{["completed", "needs_review"].includes(a.status) && <><button onClick={() => approve(a)}>Approve & set value</button><button className="ghost" onClick={() => action(a.id, "reject")}>Reject</button></>}{a.status === "approved" && <span>Awaiting payout</span>}</span></div>)}</div></section></> }
function Payouts({ items, markPaid }: any) { const groups = useMemo(() => Object.entries(items.filter((x: Payment) => x.paymentStatus !== "paid").reduce((all: Record<string, Payment[]>, p: Payment) => { const key = p.auditorEmail || "Unassigned"; (all[key] ||= []).push(p); return all; }, {})), [items]); return <><div className="stats">{groups.map(([email, list]) => <article key={email}><strong>{formatMoney((list as Payment[]).reduce((s, x) => s + (x.amount || 0), 0))}</strong><span>{(list as Payment[])[0]?.auditorName || email}<small>{(list as Payment[]).length} approved task(s)</small></span></article>)}</div><section className="panel"><div className="panelhead"><div><p className="eyebrow">PAYROLL QUEUE</p><h2>Approved work and payment history</h2></div></div><div className="table">{items.map((p: Payment) => <div className="row task" key={p.assignmentID}><span><strong>{p.title}</strong><small>{p.auditorName || "Unassigned"} · completed {formatDate(p.completedAt)}</small></span><span>{formatMoney(p.amount)}<small>{p.paymentStatus === "paid" ? `Paid ${formatDate(p.paymentDate)}` : "Awaiting payment"}</small></span><span>{p.paymentNote || "—"}</span><span className="actions">{p.paymentStatus !== "paid" && <button onClick={() => markPaid(p.assignmentID)}>Mark paid</button>}</span></div>)}</div></section></> }
function Affiliates() { return <section className="panel affiliate"><p className="eyebrow">AFFILIATE PROGRAM</p><h2>Referral and commission operations</h2><p>The payout workspace is ready for auditor compensation. The subscription-connected affiliate ledger will be enabled alongside app-store subscription verification, so recurring commissions can be calculated from verified renewals—not self-reported signups.</p><div className="steps"><span>1. Affiliate enrollment</span><span>2. Referral attribution</span><span>3. Verified subscription renewal</span><span>4. Monthly commission statement</span></div><p className="muted">Planned commission rule: $2 per referred subscriber per verified monthly renewal for the first 12 months. No affiliate earnings will be recorded until subscription verification is live.</p></section> }
function BookDrawer({ book, detail, close, call }: any) { const [transcript, setTranscript] = useState<any>(null); const [loading, setLoading] = useState(false); const getTranscript = async () => { setLoading(true); try { setTranscript(await call(`/v1/internal/admin/catalog/${book.editionID}/transcript`)); } finally { setLoading(false); } }; return <div className="overlay" onMouseDown={close}><section className="drawer" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">SCANNED EDITION</p><h2>{book.fingerprint.title}</h2><p>{book.fingerprint.author || "Unknown author"} · {book.fingerprint.edition || "Edition not specified"}</p><div className="detailstats"><span><b>{book.eventCount}</b> filter events</span><span><b>{book.scannerVersion}</b> scanner</span><span><b>{formatDate(book.scanDate)}</b> scanned</span></div><section><h3>Generated filter result</h3><p>Edition-specific filter events and scan metadata are available to the administrator.</p>{detail?.filters ? <button onClick={() => download(`${book.fingerprint.title}-filters.json`, detail.filters)}>Download filter JSON</button> : <span className="muted">Loading filters…</span>}</section><section><h3>Private transcript</h3><p>Only the generated transcript is available here; original audiobooks remain private and are never stored in the portal.</p>{!transcript ? <button onClick={getTranscript} disabled={loading}>{loading ? "Loading transcript…" : "Open transcript"}</button> : <><button className="ghost" onClick={() => download(`${book.fingerprint.title}-transcript.json`, transcript)}>Download transcript JSON</button><div className="transcript">{transcript.segments?.slice(0, 100).map((x: any, i: number) => <p key={i}><small>{Math.floor(x.startTime / 60)}:{String(Math.floor(x.startTime % 60)).padStart(2, "0")}</small>{x.text}</p>)}{transcript.segments?.length > 100 && <p className="muted">Previewing the first 100 segments. Use Download transcript JSON for the complete generated transcript.</p>}</div></>}</section></section></div> }
