"use client";

import { FormEvent, useState } from "react";

const availability = ["1–4 hours", "5–9 hours", "10–19 hours", "20+ hours"];
const experienceOptions = ["Audiobook listening or publishing", "Content moderation, ratings, or review", "Quality assurance or testing", "Accessibility or content-sensitivity work", "No related experience yet"];

export default function AuditorApplicationPage() {
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formElement = event.currentTarget;
    setStatus("sending"); setError("");
    const form = new FormData(formElement);
    const payload: Record<string, FormDataEntryValue | FormDataEntryValue[]> = Object.fromEntries(form.entries());
    payload.experience = form.getAll("experience");
    try {
      const response = await fetch("/api/auditor-application", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json().catch(() => ({})) as { error?: string };
      if (!response.ok) throw new Error(result.error || "We could not submit your application. Please try again.");
      formElement.reset(); setStatus("success");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Please try again."); setStatus("error"); }
  };

  return <main className="auditor-page">
    <nav className="nav shell" aria-label="Auditor application navigation"><a className="brand" href="/" aria-label="AudioChoice home"><img src="/audiochoice-logo.png" alt="" /><span>Audio<span>Choice</span></span></a><a className="beta-back" href="/">← Back to AudioChoice</a></nav>
    <header className="auditor-hero shell"><div><span className="beta-kicker">AUDIOCHOICE AUDITOR PROGRAM</span><h1>Help us make<br /><em>every skip better.</em></h1><p>Auditors help verify that AudioChoice’s content filters begin and end at the right moment. You review short, assigned excerpts, document what you find, and help our team improve the listening experience.</p></div><aside className="auditor-hero-card"><span>THE ROLE</span><p><b>Review assigned audio excerpts</b> for timing, category, and skip accuracy.</p><p><b>Submit clear notes</b> when a filter needs adjustment or escalation.</p><p><b>Earn for approved work</b> through a weekly, manually reviewed payout process.</p></aside></header>
    <section className="auditor-process shell"><span className="label">HOW IT WORKS</span><div><article><b>01</b><h2>Apply</h2><p>Tell us about your availability, equipment, and comfort reviewing sensitive material.</p></article><article><b>02</b><h2>Onboard</h2><p>Selected applicants receive an agreement, secure tax and payment follow-up, and portal access.</p></article><article><b>03</b><h2>Audit</h2><p>Claim an assigned job, listen to the provided review windows, and submit each result.</p></article><article><b>04</b><h2>Get paid</h2><p>Approved work appears in your weekly earnings total before manual payout.</p></article></div></section>
    <section className="auditor-expectations shell"><div><span className="label">WHAT WE’RE LOOKING FOR</span><h2>Careful listeners.<br />Clear judgment.</h2><p>You do not need to be an audiobook expert. You do need reliable headphones, close attention to timing, and the ability to make consistent, thoughtful calls about sensitive material.</p></div><ul><li><span>✓</span> At least 18 years old</li><li><span>✓</span> Comfortable reviewing sexual content, nudity, graphic violence, self-harm, and related sensitive material</li><li><span>✓</span> Able to use a phone or computer with dependable internet and headphones</li><li><span>✓</span> Willing to keep assigned excerpts, tasks, and materials confidential</li></ul></section>
    <section className="auditor-form-section" id="apply"><div className="shell auditor-form-layout"><div className="auditor-form-side"><span className="label">AUDITOR APPLICATION</span><h2>Start your application.</h2><p>We use this information only to review your application and contact you about the Auditor Program.</p><div className="auditor-note"><b>Privacy note</b><p>Do not submit tax IDs, Social Security numbers, banking details, or identity documents here. If you are conditionally approved, we’ll request any required tax and payment information through a separate secure process.</p></div></div><div className="auditor-form-card">{status === "success" ? <div className="beta-success" role="status"><span>✓</span><h3>Application received.</h3><p>Thanks for your interest in the AudioChoice Auditor Program. If we move forward, we’ll email you with next steps.</p><a className="secondary" href="/">Return to AudioChoice</a></div> : <form onSubmit={submit}>
      <fieldset><legend>About you</legend><div className="auditor-fields two-columns"><label><span>Full name</span><input name="name" autoComplete="name" required maxLength={100} /></label><label><span>Email address</span><input name="email" type="email" autoComplete="email" required maxLength={254} /></label><label><span>Phone number</span><input name="phone" type="tel" autoComplete="tel" required maxLength={30} /></label><label><span>City and state/province</span><input name="location" required maxLength={120} /></label><label><span>Country</span><input name="country" autoComplete="country-name" required maxLength={80} /></label><label><span>Hours available each week</span><select name="availability" required defaultValue=""><option value="" disabled>Select one</option>{availability.map(item => <option key={item}>{item}</option>)}</select></label></div></fieldset>
      <fieldset><legend>Experience and setup</legend><div className="auditor-choice-grid">{experienceOptions.map(item => <label key={item}><input type="checkbox" name="experience" value={item} /><span>{item}</span></label>)}</div><div className="auditor-fields two-columns compact-fields"><label><span>Primary review device</span><select name="device" required defaultValue=""><option value="" disabled>Select one</option><option>Android phone</option><option>iPhone or iPad</option><option>Mac</option><option>Windows computer</option><option>More than one device</option></select></label><label><span>Do you have headphones?</span><select name="headphones" required defaultValue=""><option value="" disabled>Select one</option><option>Yes</option><option>No</option></select></label></div><label className="auditor-full-field"><span>Relevant experience or anything else we should know <i>(optional)</i></span><textarea name="notes" maxLength={2000} rows={4} /></label></fieldset>
      <fieldset><legend>Eligibility and acknowledgements</legend><div className="auditor-radio-group"><span>For future contractor onboarding, which best describes your tax residency?</span><label><input type="radio" name="taxResidency" value="United States" required /> United States</label><label><input type="radio" name="taxResidency" value="Outside the United States" /> Outside the United States</label><label><input type="radio" name="taxResidency" value="Prefer to discuss" /> Prefer to discuss</label></div><label className="auditor-check"><input type="checkbox" name="ageConfirmed" value="accepted" required /><span>I confirm that I am at least 18 years old.</span></label><label className="auditor-check"><input type="checkbox" name="sensitiveContentConfirmed" value="accepted" required /><span>I understand that audit tasks may include sexual content, nudity, graphic violence, self-harm, or other sensitive material.</span></label><label className="auditor-check"><input type="checkbox" name="confidentialityConfirmed" value="accepted" required /><span>I agree to keep assigned content, excerpts, tasks, and audit information confidential and not copy, record, share, or distribute them.</span></label><label className="auditor-check"><input type="checkbox" name="contractorConfirmed" value="accepted" required /><span>If selected, I am willing to complete a contractor agreement and any required tax and payment setup through a secure follow-up process.</span></label><label className="auditor-check"><input type="checkbox" name="contactConsent" value="accepted" required /><span>I agree to be contacted by AudioChoice about this application and the Auditor Program.</span></label></fieldset>
      <input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><button className="primary" type="submit" disabled={status === "sending"}>{status === "sending" ? "Submitting…" : "Submit application"}<span>→</span></button>{status === "error" && <p className="form-error" role="alert">{error}</p>}</form>}</div></div></section>
    <footer className="shell beta-footer"><p className="footer-copy">© 2026 AudioChoice. Listen Your Way.</p><a href="mailto:support@audiochoiceapp.com">Questions? Contact support</a></footer>
  </main>;
}
